Config.blipColors = {
    {id=0, rgb={r = 255, g = 255, b = 255}},
    {id=1, rgb={r = 254, g = 50, b = 50}},
    {id=1, rgb={r = 150, g = 50, b = 50}},
    {id=1, rgb={r = 100, g = 50, b = 50}},
    {id=2, rgb={r = 113, g = 203, b = 113}},
    {id=3, rgb={r = 93, g = 182, b = 229}},
    {id=5, rgb={r = 238, g = 198, b = 78}},
    {id=7, rgb={r = 156, g = 110, b = 175}},
    {id=8, rgb={r = 254, g = 122, b = 195}},
    {id=9, rgb={r = 245, g = 157, b = 121}},
    {id=11, rgb={r = 141, g = 206, b = 167}},
    {id=12, rgb={r = 112, g = 168, b = 174}},
    {id=17, rgb={r = 234, g = 142, b = 80}},
    {id=20, rgb={r = 143, g = 141, b = 121}},
    {id=22, rgb={r = 175, g = 168, b = 168}},
    {id=24, rgb={r = 187, g = 214, b = 91}},
    {id=25, rgb={r = 12, g = 123, b = 86}},
    {id=29, rgb={r = 69, g = 97, b = 171}},
    {id=32, rgb={r = 200, g = 224, b = 254}},
    {id=33, rgb={r = 240, g = 240, b = 150}},
    {id=38, rgb={r = 44, g = 109, b = 184}},
    {id=38, rgb={r = 0, g = 20, b = 100}},
    {id=38, rgb={r = 0, g = 0, b = 184}},
    {id=40, rgb={r = 15, g = 15, b = 15}},
    {id=40, rgb={r = 30, g = 30, b = 30}},
    {id=40, rgb={r = 76, g = 76, b = 76}},
    {id=40, rgb={r = 100, g = 100, b = 100}},
    {id=46, rgb={r = 236, g = 240, b = 41}},
    {id=47, rgb={r = 255, g = 154, b = 24}},
    {id=76, rgb={r = 120, g = 35, b = 35}},

}


Config.blipColorIds = {
    black = 40, 
    white = 45,
    silver = 55,
    red = 1,
    pink = 8,
    blue = 38,
    yellow = 5,
    green = 2,
    orange = 47,
    brown = 10,
    purple = 27,
    chrome = 62, 
    gold = 46
}

Config.preColors = {
    black = {
        { index = 0, label = _L('black')},
        { index = 1, label = _L('graphite')},
        { index = 2, label = _L('black_metallic')},
        { index = 3, label = _L('caststeel')},
        { index = 11, label = _L('black_anth')},
        { index = 12, label = _L('matteblack')},
        { index = 15, label = _L('darknight')},
        { index = 16, label = _L('deepblack')},
        { index = 21, label = _L('oil')},
        { index = 147, label = _L('carbon')},
    },
    white = {
        { index = 106, label = _L('vanilla')},
        { index = 107, label = _L('creme')},
        { index = 111, label = _L('white')},
        { index = 112, label = _L('polarwhite')},
        { index = 113, label = _L('beige')},
        { index = 121, label = _L('mattewhite')},
        { index = 122, label = _L('snow')},
        { index = 131, label = _L('cotton')},
        { index = 132, label = _L('alabaster')},
        { index = 134, label = _L('purewhite')},
    },
    silver = {
        { index = 4, label = _L('silver')},
        { index = 5, label = _L('metallicgrey')},
        { index = 6, label = _L('laminatedsteel')},
        { index = 7, label = _L('darkgray')},
        { index = 8, label = _L('rockygray')},
        { index = 9, label = _L('graynight')},
        { index = 10, label = _L('aluminum')},
        { index = 13, label = _L('graymat')},
        { index = 14, label = _L('lightgrey')},
        { index = 17, label = _L('asphaltgray')},
        { index = 18, label = _L('grayconcrete')},
        { index = 19, label = _L('darksilver')},
        { index = 20, label = _L('magnesite')},
        { index = 22, label = _L('nickel')},
        { index = 23, label = _L('zinc')},
        { index = 24, label = _L('dolomite')},
        { index = 25, label = _L('bluesilver')},
        { index = 26, label = _L('titanium')},
        { index = 66, label = _L('steelblue')},
        { index = 93, label = _L('champagne')},
        { index = 144, label = _L('grayhunter')},
        { index = 156, label = _L('grey')},
    },
    red = {
        { index = 27, label = _L('red')},
        { index = 28, label = _L('torino_red')},
        { index = 29, label = _L('poppy')},
        { index = 30, label = _L('copper_red')},
        { index = 31, label = _L('cardinal')},
        { index = 32, label = _L('brick')},
        { index = 33, label = _L('garnet')},
        { index = 34, label = _L('cabernet')},
        { index = 35, label = _L('candy')},
        { index = 39, label = _L('matte_red')},
        { index = 40, label = _L('dark_red')},
        { index = 43, label = _L('red_pulp')},
        { index = 44, label = _L('bril_red')},
        { index = 46, label = _L('pale_red')},
        { index = 143, label = _L('wine_red')},
        { index = 150, label = _L('volcano')},
    },
    pink = {
        { index = 135, label = _L('electricpink')},
        { index = 136, label = _L('salmon')},
        { index = 137, label = _L('sugarplum')},
    },
    blue = {
        { index = 54, label = _L('topaz')},
        { index = 60, label = _L('light_blue')},
        { index = 61, label = _L('galaxy_blue')},
        { index = 62, label = _L('dark_blue')},
        { index = 63, label = _L('azure')},
        { index = 64, label = _L('navy_blue')},
        { index = 65, label = _L('lapis')},
        { index = 67, label = _L('blue_diamond')},
        { index = 68, label = _L('surfer')},
        { index = 69, label = _L('pastel_blue')},
        { index = 70, label = _L('celeste_blue')},
        { index = 73, label = _L('rally_blue')},
        { index = 74, label = _L('blue_paradise')},
        { index = 75, label = _L('blue_night')},
        { index = 77, label = _L('cyan_blue')},
        { index = 78, label = _L('cobalt')},
        { index = 79, label = _L('electric_blue')},
        { index = 80, label = _L('horizon_blue')},
        { index = 82, label = _L('metallic_blue')},
        { index = 83, label = _L('aquamarine')},
        { index = 84, label = _L('blue_agathe')},
        { index = 85, label = _L('zirconium')},
        { index = 86, label = _L('spinel')},
        { index = 87, label = _L('tourmaline')},
        { index = 127, label = _L('paradise')},
        { index = 140, label = _L('bubble_gum')},
        { index = 141, label = _L('midnight_blue')},
        { index = 146, label = _L('forbidden_blue')},
        { index = 157, label = _L('glacier_blue')},
    },
    yellow = {
        { index = 42, label = _L('yellow')},
        { index = 88, label = _L('wheat')},
        { index = 89, label = _L('raceyellow')},
        { index = 91, label = _L('paleyellow')},
        { index = 126, label = _L('lightyellow')},
    },
    green = {
        { index = 49, label = _L('met_dark_green')},
        { index = 50, label = _L('rally_green')},
        { index = 51, label = _L('pine_green')},
        { index = 52, label = _L('olive_green')},
        { index = 53, label = _L('light_green')},
        { index = 55, label = _L('lime_green')},
        { index = 56, label = _L('forest_green')},
        { index = 57, label = _L('lawn_green')},
        { index = 58, label = _L('imperial_green')},
        { index = 59, label = _L('green_bottle')},
        { index = 92, label = _L('citrus_green')},
        { index = 125, label = _L('green_anis')},
        { index = 128, label = _L('khaki')},
        { index = 133, label = _L('army_green')},
        { index = 151, label = _L('dark_green')},
        { index = 152, label = _L('hunter_green')},
        { index = 155, label = _L('matte_foilage_green')},
    },
    orange = {
        { index = 36, label = _L('tangerine')},
        { index = 38, label = _L('orange')},
        { index = 41, label = _L('matteorange')},
        { index = 123, label = _L('lightorange')},
        { index = 124, label = _L('peach')},
        { index = 130, label = _L('pumpkin')},
        { index = 138, label = _L('orangelambo')},
    },
    brown = {
        { index = 45, label = _L('copper')},
        { index = 47, label = _L('lightbrown')},
        { index = 48, label = _L('darkbrown')},
        { index = 90, label = _L('bronze')},
        { index = 94, label = _L('brownmetallic')},
        { index = 95, label = _L('Expresso')},
        { index = 96, label = _L('chocolate')},
        { index = 97, label = _L('terracotta')},
        { index = 98, label = _L('marble')},
        { index = 99, label = _L('sand')},
        { index = 100, label = _L('sepia')},
        { index = 101, label = _L('bison')},
        { index = 102, label = _L('palm')},
        { index = 103, label = _L('caramel')},
        { index = 104, label = _L('rust')},
        { index = 105, label = _L('chestnut')},
        { index = 108, label = _L('brown')},
        { index = 109, label = _L('hazelnut')},
        { index = 110, label = _L('shell')},
        { index = 114, label = _L('mahogany')},
        { index = 115, label = _L('cauldron')},
        { index = 116, label = _L('blond')},
        { index = 129, label = _L('gravel')},
        { index = 153, label = _L('darkearth')},
        { index = 154, label = _L('desert')},
    },
    purple = {
        { index = 71, label = _L('indigo')},
        { index = 72, label = _L('deeppurple')},
        { index = 76, label = _L('darkviolet')},
        { index = 81, label = _L('amethyst')},
        { index = 142, label = _L('mysticalviolet')},
        { index = 145, label = _L('purplemetallic')},
        { index = 148, label = _L('matteviolet')},
        { index = 149, label = _L('mattedeeppurple')},
    },
    chrome = {
        { index = 117, label = _L('brushedchrome')},
        { index = 118, label = _L('blackchrome')},
        { index = 119, label = _L('brushedaluminum')},
        { index = 120, label = _L('chrome')},
    },
    gold = {
        { index = 37, label = _L('gold')},
        { index = 158, label = _L('puregold')},
        { index = 159, label = _L('brushedgold')},
        { index = 160, label = _L('lightgold')}
    }
}
